# Generated by Django 4.2.4 on 2023-08-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('blog_slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('blog_text', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('blog_preview', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='Превью')),
                ('blog_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('blog_is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('blog_count', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ('blog_title',),
            },
        ),
    ]
