# Generated by Django 4.2.4 on 2023-08-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mailings.mailingstatus', verbose_name='Статус'),
        ),
    ]
