# Generated by Django 4.2.4 on 2023-08-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус попытки'),
        ),
    ]
