# Generated by Django 4.2.4 on 2023-09-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_mailinglogs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='server_response',
            field=models.TextField(default='OK', verbose_name='Ответ сервера'),
        ),
        migrations.AlterField(
            model_name='mailinglogs',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Статус попытки'),
        ),
    ]
