# Generated by Django 4.2.4 on 2023-09-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0008_alter_client_email_alter_client_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Тема'),
        ),
    ]
